os: Windows Server 2012 R2

build:
  project: Pash.proj
  verbosity: minimal

branches:
  only:
    - master

test_script:
  - ps: |
      function Add-ResultsMessage([string]$Path, [string]$Name) {
        $xml = [xml](Get-Content $Path)
        $total = $xml.'test-results'.total
        $errors = $xml.'test-results'.errors
        $failures = $xml.'test-results'.failures
        $notrun = $xml.'test-results'.'not-run'
        $inconclusive = $xml.'test-results'.inconclusive
        $ignored = $xml.'test-results'.ignored
        $skipped = $xml.'test-results'.skipped
        $invalid = $xml.'test-results'.invalid
        $script:errors += $errors + $failures

        $message = "Ran $Name. Tests run: $total, Errors: $errors, Failures: $failures, Not run: $notrun, Ignored: $ignored, Skipped: $skipped"
        Add-AppveyorMessage $message -Category $(if (($errors -ne 0) -or ($failures -ne 0)) {'Error'} else {'Information'})
      }

      function Start-NUnit($Path, $Name) {
        Tools\NUnit-2.6.1\bin\nunit-console.exe -nologo $Path /xml:results.xml

        Add-ResultsMessage results.xml $Name

        $wc = New-Object Net.WebClient
        $url = "https://ci.appveyor.com/api/testresults/nunit/$Env:APPVEYOR_JOB_ID"
        $wc.UploadFile($url, (Resolve-Path .\results.xml))
      }

      $errors = 0

      Start-Nunit Pash.nunit 'Pash tests'
      Start-Nunit WindowsPowershellReferenceTests.nunit 'Windows PowerShell reference tests'
      
      if ($errors) {
        throw "$errors tests failed."
      }
